import asyncio
import uvicorn
from datetime import datetime, timezone
from pathlib import Path
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from rich.console import Console
from typer import Exit, Typer
from app.dependencies import get_session_context
from app.models.user import User, AccountRoles, AccountStatus

ALEMBIC_INI = Path(__file__).resolve().parent / 'alembic.ini'
app = Typer()
console = Console()

def _alembic_config() -> Config:
    return Config(str(ALEMBIC_INI))

async def _new_user(email: str, password: str, role: AccountRoles):
    user = User(
        email=email,
        password=password,
        status=AccountStatus.Active,
        role=role
    )
    async with get_session_context() as session:
        session.add(user)
        await session.flush()

def _create_user_command(email: str, password: str, role: AccountRoles):
    label = 'Superuser' if role == AccountRoles.Admin else 'User'
    try:
        asyncio.run(_new_user(email, password, role))
    except Exception as e:
        console.print(f'[bold red]✗[/bold red] Failed to create {label.lower()} [cyan]{email}[/cyan]: {e}')
        raise Exit(code=1)
    console.print(f'[bold green]✓[/bold green] {label} [cyan]{email}[/cyan] created successfully')

@app.command('createuser')
def create_user(email: str, password: str):
    _create_user_command(email, password, AccountRoles.User)

@app.command('createsuperuser')
def create_superuser(email: str, password: str):
    _create_user_command(email, password, AccountRoles.Admin)

@app.command('runserver')
def run_server(host: str | None = None):
    hostname = '127.0.0.1'
    port = 3000
    portstr = str(port)

    if host is not None:
        t = host.split(':')
        if len(t) == 2:
            hostname = str(t[0])
            portstr = t[1]
        elif len(t) == 1:
            portstr = t[0]
        try:
            port = int(portstr)
        except (ValueError, TypeError):
            pass

    uvicorn.run(
        'app.main:app',
        host=hostname,
        port=port,
        log_level='info',
        reload=True
    )

@app.command('makemigrations')
def make_migrations(message: str | None = None):
    config = _alembic_config()
    script = ScriptDirectory.from_config(config)
    head = script.get_current_head()
    if message is None:
        msg_last = '' if head is None else f" from migration #{head}"
        message = f"[autogenerated] Migration covers all changes{msg_last} until {datetime.now(timezone.utc).strftime('%Y-%b-%d %I:%M:%S%p (%Z)').upper()}"
    command.revision(config, message=message, autogenerate=True)


@app.command('migrate')
def migrate(revision: str = 'head'):
    command.upgrade(_alembic_config(), revision)

def main():
    app()

if __name__ == '__main__':
    main()