"""[autogenerated] Migration covers all changes from migration #f84e74ed41be until 2026-SEP-16 06:55:43PM (UTC)

Revision ID: 07b8154cde30
Revises: f84e74ed41be
Create Date: 2026-09-16 13:55:43.823672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07b8154cde30'
down_revision: Union[str, Sequence[str], None] = 'f84e74ed41be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('User', 'Staff', 'Admin', name='accountroles').create(op.get_bind())
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('User', 'Staff', 'Admin', name='accountrole'),
               type_=sa.Enum('User', 'Staff', 'Admin', name='accountroles'),
               existing_nullable=False,
               postgresql_using='role::text::accountroles')
    sa.Enum('User', 'Staff', 'Admin', name='accountrole').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('User', 'Staff', 'Admin', name='accountrole').create(op.get_bind())
    op.alter_column('users', 'role',
               existing_type=sa.Enum('User', 'Staff', 'Admin', name='accountroles'),
               type_=postgresql.ENUM('User', 'Staff', 'Admin', name='accountrole'),
               existing_nullable=False)
    sa.Enum('User', 'Staff', 'Admin', name='accountroles').drop(op.get_bind())
    # ### end Alembic commands ###
