"""[autogenerated] Migration covers all changes from migration #07b8154cde30 until 2026-SEP-16 07:47:27PM (UTC)

Revision ID: 88712eefb07c
Revises: 07b8154cde30
Create Date: 2026-09-16 14:47:27.436751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88712eefb07c'
down_revision: Union[str, Sequence[str], None] = '07b8154cde30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('schema_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'fields', 'schemas', ['schema_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'fields', type_='foreignkey')
    op.drop_column('fields', 'schema_id')
    # ### end Alembic commands ###
