"""[autogenerated] Migration covers all changes until 2026-SEP-15 09:15:20PM (UTC)

Revision ID: f84e74ed41be
Revises: 
Create Date: 2026-09-15 16:15:20.990043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f84e74ed41be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('User', 'Staff', 'Admin', name='accountrole').create(op.get_bind())
    sa.Enum('Unverified', 'Active', 'Deleted', name='accountstatus').create(op.get_bind())
    op.create_table('fields',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('generator', sa.String(length=255), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('autoid', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fields_autoid'), 'fields', ['autoid'], unique=True)
    op.create_index(op.f('ix_fields_name'), 'fields', ['name'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', postgresql.ENUM('Unverified', 'Active', 'Deleted', name='accountstatus', create_type=False), nullable=False),
    sa.Column('role', postgresql.ENUM('User', 'Staff', 'Admin', name='accountrole', create_type=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('autoid', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_autoid'), 'users', ['autoid'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('schemas',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('autoid', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schemas_autoid'), 'schemas', ['autoid'], unique=True)
    op.create_table('sessions',
    sa.Column('pysessid_hash', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=40), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('autoid', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_autoid'), 'sessions', ['autoid'], unique=True)
    op.create_index(op.f('ix_sessions_pysessid_hash'), 'sessions', ['pysessid_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_pysessid_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_autoid'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_schemas_autoid'), table_name='schemas')
    op.drop_table('schemas')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_autoid'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_fields_name'), table_name='fields')
    op.drop_index(op.f('ix_fields_autoid'), table_name='fields')
    op.drop_table('fields')
    sa.Enum('Unverified', 'Active', 'Deleted', name='accountstatus').drop(op.get_bind())
    sa.Enum('User', 'Staff', 'Admin', name='accountrole').drop(op.get_bind())
    # ### end Alembic commands ###
